enum _code_t
{
  UNINITIALIZED=0,

  COMMAND_INCREMENT=1,
  COMMAND_DECREMENT=2,
  COMMAND_SET_VOLTS=3,
  COMMAND_SET_CODE=4,
  COMMAND_CALIBRATE_OP_AMP_GAIN=5,
  COMMAND_CALIBRATE_LM317_VREF=6,
  
  END_OF_COMMANDS_SECTION=7,

  OK_NO_ERROR=10,
  ERROR_UNKNOWN_COMMAND=11,
  ERROR_BUFFER_FILLED_UP_BEFORE_SENTINEL_REACHED=12,

  ERROR_INCREMENT_WOULD_CAUSE_OVERFLOW=20,
  ERROR_DECREMENT_WOULD_CAUSE_UNDERFLOW=21,

  ERROR_PARSED_VOLTAGE_OUTSIDE_SUPPORTED_RANGE=30,
  ERROR_PARSED_CODE_OUTSIDE_SUPPORTED_RANGE=40,
  
  ERROR_PARSED_GAIN_OUTSIDE_SUPPORTED_RANGE=50,
  ERROR_PARSED_VREF_OUTSIDE_SUPPORTED_RANGE=60
};

typedef enum _code_t command_t;
typedef enum _code_t error_t;

