enum _code_t
{
  UNINITIALIZED=0,
  COMMAND_INCREMENT=1,
  COMMAND_DECREMENT=2,
  COMMAND_SET_VOLTS=3,
  COMMAND_SET_HEX=4,
  END_OF_COMMANDS_SECTION=5,
  OK_NO_ERROR=6,
  ERROR_UNKNOWN_COMMAND=7,
  ERROR_BUFFER_FILLED_UP_BEFORE_SENTINEL_REACHED=8,
  ERROR_INCREMENT_WOULD_CAUSE_OVERFLOW=9,
  ERROR_DECREMENT_WOULD_CAUSE_UNDERFLOW=10,
  ERROR_PARSING_INCREMENT_COMMAND=11,
  ERROR_PARSING_DECREMENT_COMMAND=12,
  ERROR_BUFFER_FILLED_UP_BEFORE_SENTINEL_REACHED_WHILE_PARSING_HEX_COMMAND=13,
  ERROR_BUFFER_FILLED_UP_BEFORE_SENTINEL_REACHED_WHILE_PARSING_VOLTS_COMMAND=14,
  ERROR_PARSING_HEX_VALUE=15
};

typedef enum _code_t command_t;
typedef enum _code_t error_t;

